### PR TITLE
kegg parameter change

### PR DESCRIPTION
**Pull request by kkleinoros**
correction to download kegg.db

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
@huerqiang pls check whether these changes are necessary.

**Comment by huerqiang** [comment]
@kkleinoros I don't know the reason for your amendment. Please explain it in detail.

**Comment by huerqiang** [comment]
(1) As far as I know, it is necessory to use `species <- organismMapper(organism)`. It will report error without using organismMapper() function. In addition, the current version should not have the KEGG download problem.
(2) We have delcared enricher_internal and GSEA_internal in utilities.R. Of course, using getFromNamespace in DOSE.R is a better choice, and we will change it in the next version.

**Comment by kkleinoros** [comment]
Look at the number of issues reported on your github page, I suggest you check it out.
kathleen

**Comment by huerqiang** [comment]
@kkleinoros Please update your packages.
@GuangchuangYu I think we should reject this PR. There is no such problem in the latest version, and the PR will cause errors.

**Pull request closed without merging**
