### PR TITLE
update `simplify` function to support `ont = ALL`

### PR DESCRIPTION
**Pull request by huerqiang**
update `simplify` function to support `ont = ALL` for `enrichResult`, `gseaResult` and `compareClusterResult`
[simplify.pdf](https://github.com/YuLab-SMU/clusterProfiler/files/7426737/simplify.pdf)

### CODE REVIEW

**Comment by Riverhuang42** [comment]
Hi I am using clusterProfiler’ version 4.0.5, the simplify function still not support ont = ALL for me, It works with ont=bp and others. 

> enrichgo<-enrichGO(RNA_Protein_padj_in_gene,keyType = "SYMBOL",'org.Mm.eg.db',ont="ALL",qvalueCutoff = 0.05)
> enrichgo_sim<-simplify(enrichgo)
Error in .local(x, ...) : 
  simplify only applied to output from gsegO and enrichGO...

**Comment by Riverhuang42** [comment]
Hi,  I am using clusterProfiler’ version 4.0.5 and trying to use simplify for ont=ALL, but it still doesn't work for me. Could you please some suggestions? Thanks！

RNA_Protein_padj_enrichgo_in<-enrichGO(RNA_Protein_padj_in_gene,keyType = "SYMBOL",'org.Mm.eg.db',ont="ALL",qvalueCutoff = 0.05)
> RNA_Protein_padj_enrichgo_in_all_sim<-simplify(RNA_Protein_padj_enrichgo_in)
Error in .local(x, ...) : 
  simplify only applied to output from gsegO and enrichGO...

**Comment by huerqiang** [comment]
@Riverhuang42 Are you using the latest version of `clusterProfiler`?

**Comment by Riverhuang42** [comment]
> @Riverhuang42 Are you using the latest version of `clusterProfiler`?

Yes, I use 4.2.2

**Comment by huerqiang** [comment]
@Riverhuang42 Please try the Github version.

**Comment by Riverhuang42** [comment]
> 

Thanks, it works for me now!

**Pull request merged**
