### PR TITLE
Dynamically get function from either DOSE or clusterProfiler 

### PR DESCRIPTION
**Pull request by Nelson-Gon**
Hi, 

This pull request removes the eval-parse framework and additionally asserts that only allowed choices can be supplied.

It is also related to  https://github.com/YuLab-SMU/clusterProfiler/issues/412

Thank you,

NelsonGon

### CODE REVIEW

**Comment by huerqiang** [comment]
The `compareCluster` supports  not only the functions of  `clusterProfiler` and `DOSE`, but also functions from other sources, as well as user-defined functions.

**Comment by Nelson-Gon** [comment]
Thanks @huerqiang From the doc entry it seems to only support `DOSE` and `clusterProfiler`, perhaps the doc needs an update too?

>##' @param fun One of "groupGO", "enrichGO", "enrichKEGG", "enrichDO" or "enrichPathway" .

**Comment by huerqiang** [comment]
@Nelson-Gon  YYes, I think you can also update the documents in this PR.

**Comment by GuangchuangYu** [comment]
thanks.

**Pull request merged**
